### ISSUE TITLE
[BUG] Wallpaper not applying on editor and terminal

### ISSUE THREAD

**Issue by JackBlaze132** [RichardLuo0/vscode-frosted-glass-theme#15]
I have defined the desired wallpaper to appear and also and also defined the blur filter but I got no changes on my UI
![image](https://github.com/user-attachments/assets/1413ec7b-c35d-40e1-9702-ccca78a0b720)
I know the image URL is correct due to it is appearing in my title bar, anyone knows how to solve this issue?

**Comment by RichardLuo0** [comment]
**You need to change the theme colors as well since this extension does not apply opacity to your theme automatically.**

There are some examples in https://github.com/RichardLuo0/vscode-frosted-glass-theme/tree/dev/theme.
Try `workbench.action.generateColorTheme` command, and add transparency to the extracted color. Then add them to `workbench.colorCustomizations`

**Comment by RichardLuo0** [comment]
I need to close this. If you need further help, feel free to reopen
